# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('coach_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=201)),
                ('from_year', models.IntegerField(default=2015)),
                ('to_year', models.IntegerField(default=2015)),
                ('years', models.IntegerField(default=0)),
                ('reg_season_games', models.IntegerField(default=0)),
                ('reg_season_wins', models.IntegerField(default=0)),
                ('reg_season_losses', models.IntegerField(default=0)),
                ('reg_season_w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('above_500', models.DecimalField(max_digits=5, decimal_places=1, null=True)),
                ('post_season_games', models.IntegerField(default=0, null=True)),
                ('post_season_wins', models.IntegerField(default=0, null=True)),
                ('post_season_losses', models.IntegerField(default=0, null=True)),
                ('post_season_w_pct', models.DecimalField(max_digits=4, decimal_places=3, null=True)),
                ('conference_champs', models.IntegerField(default=0, null=True)),
                ('league_champs', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('player_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_first_last', models.CharField(max_length=201)),
                ('display_last_comma_first', models.CharField(max_length=202)),
                ('display_fi_last', models.CharField(max_length=102)),
                ('birthdate', models.DateField()),
                ('school', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('last_affiliation', models.CharField(max_length=200, null=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('season_exp', models.IntegerField(default=0)),
                ('jersey', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=40, null=True)),
                ('roster_status', models.CharField(max_length=20, null=True)),
                ('team_name', models.CharField(max_length=200, null=True)),
                ('team_abbreviation', models.CharField(max_length=3, null=True)),
                ('team_code', models.CharField(max_length=50, null=True)),
                ('team_city', models.CharField(max_length=100, null=True)),
                ('playercode', models.CharField(max_length=100, null=True)),
                ('from_year', models.IntegerField(default=2015)),
                ('to_year', models.IntegerField(default=2015)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='PlayerAdvancedSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_id', models.IntegerField()),
                ('season_type', models.CharField(max_length=100)),
                ('career_flag', models.BooleanField()),
                ('player_name', models.CharField(max_length=200)),
                ('team_abbreviation', models.CharField(max_length=5)),
                ('player_age', models.IntegerField()),
                ('gp', models.IntegerField(default=0)),
                ('gs', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.IntegerField()),
                ('u_per', models.DecimalField(max_digits=3, decimal_places=1)),
                ('per', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ts_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3_ar', models.DecimalField(max_digits=3, decimal_places=3)),
                ('ft_ar', models.DecimalField(max_digits=3, decimal_places=3)),
                ('oreb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dreb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('reb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ast_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('stl_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('blk_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('tov_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('usg_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ows', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dws', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ws', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ws_48', models.DecimalField(max_digits=3, decimal_places=3)),
                ('obpm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dbpm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('bpm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('vorp', models.DecimalField(max_digits=3, decimal_places=1)),
                ('player', models.ForeignKey(to='stats.Player')),
            ],
            options={
                'db_table': 'player_advanced_season',
            },
        ),
        migrations.CreateModel(
            name='PlayerPerGameSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_id', models.IntegerField()),
                ('season_type', models.CharField(max_length=100)),
                ('career_flag', models.BooleanField()),
                ('player_name', models.CharField(max_length=200)),
                ('team_abbreviation', models.CharField(max_length=5)),
                ('player_age', models.IntegerField()),
                ('gp', models.IntegerField(default=0)),
                ('gs', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fgm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fga', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3m', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg3a', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg3_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ftm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fta', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ft_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('oreb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dreb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('reb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ast', models.DecimalField(max_digits=3, decimal_places=1)),
                ('stl', models.DecimalField(max_digits=3, decimal_places=1)),
                ('blk', models.DecimalField(max_digits=3, decimal_places=1)),
                ('blka', models.DecimalField(max_digits=3, decimal_places=1)),
                ('tov', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pf', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pfd', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pts', models.DecimalField(max_digits=3, decimal_places=1)),
                ('plus_minus', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dd2', models.IntegerField(default=0)),
                ('td3', models.IntegerField(default=0)),
                ('player', models.ForeignKey(to='stats.Player')),
            ],
            options={
                'db_table': 'player_per_game_season',
            },
        ),
        migrations.CreateModel(
            name='PlayerTotalSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_id', models.IntegerField()),
                ('season_type', models.CharField(max_length=100)),
                ('career_flag', models.BooleanField()),
                ('player_name', models.CharField(max_length=200)),
                ('team_abbreviation', models.CharField(max_length=5)),
                ('player_age', models.IntegerField()),
                ('gp', models.IntegerField(default=0)),
                ('gs', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('blka', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pfd', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('dd2', models.IntegerField(default=0)),
                ('td3', models.IntegerField(default=0)),
                ('player', models.ForeignKey(to='stats.Player')),
            ],
            options={
                'db_table': 'player_total_season',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('ref_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ref_name', models.CharField(max_length=201)),
                ('birthdate', models.DateField()),
                ('school', models.CharField(max_length=100)),
                ('jersey', models.IntegerField()),
            ],
            options={
                'db_table': 'referees',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('team_id', models.IntegerField()),
                ('team_city', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('team_abbreviation', models.CharField(max_length=5)),
                ('team_conference', models.CharField(max_length=4)),
                ('team_division', models.CharField(max_length=25)),
                ('team_code', models.CharField(max_length=25)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('conf_rank', models.IntegerField()),
                ('div_rank', models.IntegerField()),
                ('min_year', models.IntegerField()),
                ('max_year', models.IntegerField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamAdvancedSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_type', models.CharField(max_length=100)),
                ('season_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('gp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.IntegerField()),
                ('off_rating', models.DecimalField(max_digits=4, decimal_places=1)),
                ('def_rating', models.DecimalField(max_digits=4, decimal_places=1)),
                ('net_rating', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ast_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ast_to', models.DecimalField(max_digits=3, decimal_places=2)),
                ('ast_ratio', models.DecimalField(max_digits=3, decimal_places=1)),
                ('oreb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dreb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('reb_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('tm_tov_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('efg_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ts_pct', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pace', models.DecimalField(max_digits=5, decimal_places=2)),
                ('pie', models.DecimalField(max_digits=3, decimal_places=1)),
                ('team', models.ForeignKey(to='stats.Team')),
            ],
            options={
                'db_table': 'team_advanced_season',
            },
        ),
        migrations.CreateModel(
            name='TeamPerGameSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_type', models.CharField(max_length=100)),
                ('season_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('gp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fgm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fga', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3m', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg3a', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fg3_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ftm', models.DecimalField(max_digits=3, decimal_places=1)),
                ('fta', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ft_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('oreb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('dreb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('reb', models.DecimalField(max_digits=3, decimal_places=1)),
                ('ast', models.DecimalField(max_digits=3, decimal_places=1)),
                ('stl', models.DecimalField(max_digits=3, decimal_places=1)),
                ('blk', models.DecimalField(max_digits=3, decimal_places=1)),
                ('blka', models.DecimalField(max_digits=3, decimal_places=1)),
                ('tov', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pf', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pfd', models.DecimalField(max_digits=3, decimal_places=1)),
                ('pts', models.DecimalField(max_digits=3, decimal_places=1)),
                ('plus_minus', models.DecimalField(max_digits=3, decimal_places=1)),
                ('team', models.ForeignKey(to='stats.Team')),
            ],
            options={
                'db_table': 'team_per_game_season',
            },
        ),
        migrations.CreateModel(
            name='TeamTotalSeason',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('season_type', models.CharField(max_length=100)),
                ('season_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('gp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('l', models.IntegerField()),
                ('w_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('min', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.DecimalField(max_digits=4, decimal_places=3)),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.IntegerField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('blka', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pfd', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('team', models.ForeignKey(to='stats.Team')),
            ],
            options={
                'db_table': 'team_total_season',
            },
        ),
        migrations.AddField(
            model_name='playertotalseason',
            name='team',
            field=models.ForeignKey(to='stats.Team'),
        ),
        migrations.AddField(
            model_name='playerpergameseason',
            name='team',
            field=models.ForeignKey(to='stats.Team'),
        ),
        migrations.AddField(
            model_name='playeradvancedseason',
            name='team',
            field=models.ForeignKey(to='stats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(to='stats.Team'),
        ),
    ]
